export enum KnowlodgeArea {
    CIENCIAS_SOCIALES = 'CIENCIAS_SOCIALES',
    BIOLOGIA = 'BIOLOGIA',
    QUIMICA = 'BIOLOGIA',
    FISICA = 'FISICA',
    LITERATURA = 'LITERATURA',
    ETICA = 'ETICA',
    INGENIERIA = 'INGENIERÍA'
}