export enum KnowlodgeArea {
    LITERATURE = 'LITERATURE',
    SCIENCE = 'SCIENCE',
    HISTORY = 'HISTORY',
    PHILOSOPHY = 'PHILOSOPHY',
    ART = 'ART',
    TECHNOLOGY = 'TECHNOLOGY',
    MEDICINE = 'MEDICINE',
    LAW = 'LAW',
    ECONOMICS = 'ECONOMICS',
    PSYCHOLOGY = 'PSYCHOLOGY'
}