export enum GenreDto {
    FANTASY = 'FANTASY',
    SCIENCE_FICTION = 'SCIENCE_FICTION',
    MYSTERY = 'MYSTERY',
    THRILLER = 'THRILLER',
    ROMANCE = 'ROMANCE',
    WESTERN = 'WESTERN',
    DYSTOPIAN = 'DYSTOPIAN',
    ADVENTURE = 'ADVENTURE',
    HORROR = 'HORROR',
    HISTORICAL_FICTION = 'HISTORICAL_FICTION'
}